server:
  port: 8088

spring:
  application:
    name: prescription-service
  datasource:
    url: jdbc:postgresql://localhost:5438/prescriptiondb
    username: prescription
    password: prescription
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info
