apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-auth
  namespace: medilink
spec:
  serviceName: postgres-auth
  replicas: 1
  selector:
    matchLabels:
      app: postgres-auth
  template:
    metadata:
      labels:
        app: postgres-auth
    spec:
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: POSTGRES_DB
              value: authdb
            - name: POSTGRES_USER
              value: auth
            - name: POSTGRES_PASSWORD
              value: auth
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-auth
  namespace: medilink
spec:
  selector:
    app: postgres-auth
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-appointment
  namespace: medilink
spec:
  serviceName: postgres-appointment
  replicas: 1
  selector:
    matchLabels:
      app: postgres-appointment
  template:
    metadata:
      labels:
        app: postgres-appointment
    spec:
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: POSTGRES_DB
              value: appointmentdb
            - name: POSTGRES_USER
              value: appointment
            - name: POSTGRES_PASSWORD
              value: appointment
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-appointment
  namespace: medilink
spec:
  selector:
    app: postgres-appointment
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-doctor
  namespace: medilink
spec:
  serviceName: postgres-doctor
  replicas: 1
  selector:
    matchLabels:
      app: postgres-doctor
  template:
    metadata:
      labels:
        app: postgres-doctor
    spec:
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: POSTGRES_DB
              value: doctordb
            - name: POSTGRES_USER
              value: doctor
            - name: POSTGRES_PASSWORD
              value: doctor
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-doctor
  namespace: medilink
spec:
  selector:
    app: postgres-doctor
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-payment
  namespace: medilink
spec:
  serviceName: postgres-payment
  replicas: 1
  selector:
    matchLabels:
      app: postgres-payment
  template:
    metadata:
      labels:
        app: postgres-payment
    spec:
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: POSTGRES_DB
              value: paymentdb
            - name: POSTGRES_USER
              value: payment
            - name: POSTGRES_PASSWORD
              value: payment
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-payment
  namespace: medilink
spec:
  selector:
    app: postgres-payment
  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-patient
  namespace: medilink
spec:
  serviceName: postgres-patient
  replicas: 1
  selector:
    matchLabels:
      app: postgres-patient
  template:
    metadata:
      labels:
        app: postgres-patient
    spec:
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: POSTGRES_DB
              value: patientdb
            - name: POSTGRES_USER
              value: patient
            - name: POSTGRES_PASSWORD
              value: patient
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-patient
  namespace: medilink
spec:
  selector:
    app: postgres-patient
  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-telemedicine
  namespace: medilink
spec:
  serviceName: postgres-telemedicine
  replicas: 1
  selector:
    matchLabels:
      app: postgres-telemedicine
  template:
    metadata:
      labels:
        app: postgres-telemedicine
    spec:
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: POSTGRES_DB
              value: telemedicinedb
            - name: POSTGRES_USER
              value: telemedicine
            - name: POSTGRES_PASSWORD
              value: telemedicine
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-telemedicine
  namespace: medilink
spec:
  selector:
    app: postgres-telemedicine
  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-prescription
  namespace: medilink
spec:
  serviceName: postgres-prescription
  replicas: 1
  selector:
    matchLabels:
      app: postgres-prescription
  template:
    metadata:
      labels:
        app: postgres-prescription
    spec:
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: POSTGRES_DB
              value: prescriptiondb
            - name: POSTGRES_USER
              value: prescription
            - name: POSTGRES_PASSWORD
              value: prescription
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-prescription
  namespace: medilink
spec:
  selector:
    app: postgres-prescription
  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-notification
  namespace: medilink
spec:
  serviceName: postgres-notification
  replicas: 1
  selector:
    matchLabels:
      app: postgres-notification
  template:
    metadata:
      labels:
        app: postgres-notification
    spec:
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: POSTGRES_DB
              value: notificationdb
            - name: POSTGRES_USER
              value: notification
            - name: POSTGRES_PASSWORD
              value: notification
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-notification
  namespace: medilink
spec:
  selector:
    app: postgres-notification
  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-symptom
  namespace: medilink
spec:
  serviceName: postgres-symptom
  replicas: 1
  selector:
    matchLabels:
      app: postgres-symptom
  template:
    metadata:
      labels:
        app: postgres-symptom
    spec:
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: POSTGRES_DB
              value: symptomdb
            - name: POSTGRES_USER
              value: symptom
            - name: POSTGRES_PASSWORD
              value: symptom
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-symptom
  namespace: medilink
spec:
  selector:
    app: postgres-symptom
  ports:
    - port: 5432
      targetPort: 5432
