apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-auth
  namespace: medilink
spec:
  serviceName: postgres-auth
  replicas: 1
  selector:
    matchLabels:
      app: postgres-auth
  template:
    metadata:
      labels:
        app: postgres-auth
    spec:
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: POSTGRES_DB
              value: authdb
            - name: POSTGRES_USER
              value: auth
            - name: POSTGRES_PASSWORD
              value: auth
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-auth
  namespace: medilink
spec:
  selector:
    app: postgres-auth
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-appointment
  namespace: medilink
spec:
  serviceName: postgres-appointment
  replicas: 1
  selector:
    matchLabels:
      app: postgres-appointment
  template:
    metadata:
      labels:
        app: postgres-appointment
    spec:
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: POSTGRES_DB
              value: appointmentdb
            - name: POSTGRES_USER
              value: appointment
            - name: POSTGRES_PASSWORD
              value: appointment
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-appointment
  namespace: medilink
spec:
  selector:
    app: postgres-appointment
  ports:
    - port: 5432
      targetPort: 5432

