apiVersion: v1
kind: Secret
metadata:
  name: medilink-secrets
  namespace: medilink
type: Opaque
stringData:
  JWT_SECRET: "change-me-to-a-long-32bytes-min-secret-change-me"
  AUTH_DB_URL: "jdbc:postgresql://postgres-auth:5432/authdb"
  AUTH_DB_USER: "auth"
  AUTH_DB_PASS: "auth"
  APPT_DB_URL: "jdbc:postgresql://postgres-appointment:5432/appointmentdb"
  APPT_DB_USER: "appointment"
  APPT_DB_PASS: "appointment"

