apiVersion: v1
kind: Secret
metadata:
  name: medilink-secrets
  namespace: medilink
type: Opaque
stringData:
  JWT_SECRET: "change-me-to-a-long-32bytes-min-secret-change-me"
  AUTH_DB_URL: "jdbc:postgresql://postgres-auth:5432/authdb"
  AUTH_DB_USER: "auth"
  AUTH_DB_PASS: "auth"
  APPT_DB_URL: "jdbc:postgresql://postgres-appointment:5432/appointmentdb"
  APPT_DB_USER: "appointment"
  APPT_DB_PASS: "appointment"
  DOCTOR_DB_URL: "jdbc:postgresql://postgres-doctor:5432/doctordb"
  DOCTOR_DB_USER: "doctor"
  DOCTOR_DB_PASS: "doctor"
  PAYMENT_DB_URL: "jdbc:postgresql://postgres-payment:5432/paymentdb"
  PAYMENT_DB_USER: "payment"
  PAYMENT_DB_PASS: "payment"
  PATIENT_DB_URL: "jdbc:postgresql://postgres-patient:5432/patientdb"
  PATIENT_DB_USER: "patient"
  PATIENT_DB_PASS: "patient"
  PAYHERE_MERCHANT_ID: "1211149"
  PAYHERE_MERCHANT_SECRET: "CHANGE_ME_PAYHERE_SECRET"
