server:
  port: 8085

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5435/paymentdb
    username: payment
    password: payment
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

app:
  appointment-base-url: http://localhost:8082
  patient-base-url: http://localhost:8086
  gateway-base-url: http://localhost:8090
  frontend-base-url: http://localhost:5173

payhere:
  sandbox: true
  merchant-id: "change-me"
  merchant-secret: "change-me"
  sandbox-checkout-url: https://sandbox.payhere.lk/pay/checkout
  live-checkout-url: https://www.payhere.lk/pay/checkout

stripe:
  secret-key: ${STRIPE_SECRET_KEY:}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET:}

management:
  endpoints:
    web:
      exposure:
        include: health,info
