server:
  port: 8084

spring:
  application:
    name: doctor-service
  datasource:
    url: jdbc:postgresql://localhost:5434/doctordb
    username: doctor
    password: doctor
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info

