server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: auth
    password: auth
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

security:
  jwt:
    secret: "change-me-to-a-long-32bytes-min-secret-change-me"
    ttl-seconds: 3600

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info
